### ISSUE TITLE
建议每次抓取发布到Releases中，并且标注下数据的具体月日

### ISSUE THREAD

**Issue by ppoffice** [kakuilan/china_area_mysql#1]
首先感谢分享，最近项目中正好用到。
如果将每次的结果发布到Release中的话，方便管理和下载，另外也不用将历次的版本都放到Repo中了。
另外可以使用数据发布的年月日来替代抓取的年月日来命名发布的文件，这样方便用户去国家统计局对应查找。
一点小小的建议，希望能采纳:smile:

**Comment by kakuilan** [comment]
好的，谢谢，有空我改一下
