### ISSUE TITLE
表结构的字段类型有误

### ISSUE THREAD

**Issue by peterZhaChina** [kakuilan/china_area_mysql#10]
表结构的字段类型有误和数据文件中的字段不一致，导致建表后数据会导入失败需要手动调整。建议直接用工具生成可执行 SQL 文件存储。用起来会方便。

**Comment by kakuilan** [comment]
README中的表结构和cnarea20150930.7z中是一样的，目前是最新的数据；你是不是下错数据了？

**Comment by peterZhaChina** [comment]
使用的是 cnarea20160320-2.sql

**Comment by kakuilan** [comment]
...那是2014年的数据，不是最新的
