### ISSUE TITLE
数据少

### ISSUE THREAD

**Issue by lengrongfu** [kakuilan/china_area_mysql#18]
我下载的是20160731这个包，导入数据之后之后5个省份的数据，总的只有100594条，这是什么原因？

**Comment by kakuilan** [comment]
没有完整导入吧，你看看中途有什么报错吗

**Comment by lengrongfu** [comment]
刚刚已经导好了，问题是我开始用工具导入，每次都只能导入100594条就停止了，后来我用命令行导入就可以了，所以没有问题了，谢谢哈。
