### ISSUE TITLE
关于数据中经纬度的问题

### ISSUE THREAD

**Issue by herrygoon** [kakuilan/china_area_mysql#21]
感谢提供的数据!! 有个疑问：
看到一个issue中提到，用的是百度API获取的地图坐标(https://github.com/kakuilan/china_area_mysql/issues/6)
但是实际从百度地图中查询的时候，发现还有很大的差距。是否还需要进行某种转换呢？
如以王府井社区居委会为例，给的地理坐标为116.402913,39.91402,而实际的应该是116.421223,39.920574
![image](https://user-images.githubusercontent.com/473702/36886184-05a2a52a-1e26-11e8-9802-be6fa875c489.png)

![image](https://user-images.githubusercontent.com/473702/36886173-fb654bb2-1e25-11e8-8a14-ad9e4cf919f1.png)

**Comment by kakuilan** [comment]
我采集高德的，应该需要转换

**Comment by herrygoon** [comment]
好的。不知道高德这块是怎么采集的，也是api？但是看实际的高德地图也还是有一些差别。

**Comment by kakuilan** [comment]
按merger_name去查，没怎么注意有误差，下版看看怎么改进

**Comment by kakuilan** [comment]
@herrygoon 2017新版已修复
