### ISSUE TITLE
请问城市区号在哪里查询。

### ISSUE THREAD

**Issue by l619534951** [kakuilan/china_area_mysql#22]
有没有官网呢？还是来自第三方的数据呀？

**Comment by YonSunZhen** [comment]
国家统计局可以查好像

**Comment by l619534951** [comment]
@YonSunZhen 我找了，没找到，只能找到行政区划代码

**Comment by kakuilan** [comment]
https://lbs.amap.com/api/webservice/guide/api/georegeo
