### ISSUE TITLE
有爬取港澳台三级行政区域的代码吗

### ISSUE THREAD

**Issue by mansoncui** [kakuilan/china_area_mysql#26]
有爬取港澳台三级行政区域的代码吗，能发来参考下吗

**Comment by kakuilan** [comment]
不好意思，爬虫是集成在公司一个系统里面的，还没拆出来，不方便哦
台湾地区的数据源 https://twn.youbianku.com/zh-hans
港澳的没找到好的数据源

**Comment by mansoncui** [comment]
你这边是怎么爬取网页数据的，交流下，相互学习下






在 2018-09-26 23:18:05，"kakuilan" <notifications@github.com> 写道：


不好意思，爬虫是集成在公司一个系统里面的，还没拆出来，不方便哦
台湾地区的数据源 https://twn.youbianku.com/zh-hans
港澳的没找到好的数据源
