### ISSUE TITLE
请问拼音您是用什么库或者接口之类的获取到的呢？

### ISSUE THREAD

**Issue by xiangyuecn** [kakuilan/china_area_mysql#28]
从cnarea20171031中抽样看了一下那些简称包括多音字都拼的很正确，70多万个名字用什么工具能拼得这么好呢？

另外建议一下insert那句每条数据应该可以换一下行，UltraEdit上打开来看都比较吃力，批量换行一下后好多了。

**Comment by kakuilan** [comment]
1、使用overtrue/pinyin
2、SQL是工具导出的,不好弄一个insert一条语句

**Comment by xiangyuecn** [comment]
@kakuilan 学习了:smile:
