### ISSUE TITLE
老铁，18年的好像出来了，有空整一下子

### ISSUE THREAD

**Issue by Geek-007** [kakuilan/china_area_mysql#32]
![image](https://user-images.githubusercontent.com/25733662/55058022-ccf5d680-50a5-11e9-80eb-e1d02349c5d1.png)

**Comment by kakuilan** [comment]
好，这几天整理下

**Comment by kakuilan** [comment]
还在跑，这周内应该可以，调整了表结构

**Comment by kakuilan** [comment]
@Geek-007 @qiuqiuX 2018数据已更新
