### ISSUE TITLE
貌似东莞市下面的县级全部都没有

### ISSUE THREAD

**Issue by wh469012917** [kakuilan/china_area_mysql#4]
如题，东莞市下面都没了，是忘记了还是没查到？

**Comment by kakuilan** [comment]
确实，谢谢反馈，过几天再爬一轮

**Comment by wh469012917** [comment]
你看这两天可否处理下，现在要用a到

**Comment by kakuilan** [comment]
重新爬一遍要4天，这两天不大可能搞完...

**Comment by LaserPlasma** [comment]
东莞市是筒子市下面没有县级，直接到街道。全国还有几个“筒子市”。百度可以看一下。

**Comment by kakuilan** [comment]
近来有点事情，暂时抽不出时间爬数据...

**Comment by cheneason** [comment]
你的mysql用的是哪个版本呢？我这5.6的导入总是出问题呀

**Comment by wh469012917** [comment]
应该是5.6或者5.7吧，具体不清。

**Comment by cheneason** [comment]
ERROR 1231 (42000): Variable 'sql_mode' can't be set to the value of 'NULL'
ERROR 1231 (42000): Variable 'unique_checks' can't be set to the value of 'NULL'
总遇到这样的问题，是怎么回事呢？
