### ISSUE TITLE
查询很费时阿？

### ISSUE THREAD

**Issue by sapceman** [kakuilan/china_area_mysql#44]
PHP查询语句:SELECT `id`,`level`,`name`,`short_name`,`merger_name`,`pinyin`,`lng`,`lat` FROM `map_cnarea_2018` WHERE `short_name`='$query' ORDER BY `level`
耗时5秒多，通过分析，Creating Sort Index 耗时就5秒。请问大神，如何解决？

**Comment by kakuilan** [comment]
你自己创建相应的索引就行

**Comment by sapceman** [comment]
加了索引，问题解决了。
