### ISSUE TITLE
大牛，新年好。请问有无数据最新更新计划？

### ISSUE THREAD

**Issue by stellar2016** [kakuilan/china_area_mysql#46]
大牛，新年好。请问有无数据最新更新计划？
---cnarea20181031.7z是爬取2018年的数据,截止2018年10月31日.
马上都2020年了

**Comment by kakuilan** [comment]
最近比较忙，还没计划更新。而且2019的数据也没出来。

**Comment by yl-yue** [comment]
货比三家才发现你的好，爱了

**Comment by Geek-007** [comment]
> 最近比较忙，还没计划更新。而且2019的数据也没出来。

2019年的出来了，有时间可以跑跑[http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2019/index.html](url)

**Comment by yl-yue** [comment]
> > 最近比较忙，还没计划更新。而且2019的数据也没出来。
> 
> 2019年的出来了，有时间可以跑跑[http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2019/index.html](url)

更新了又得同步好累的样子，我这边表结构有更改

**Comment by kakuilan** [comment]
有点忙，说不定啥时候弄

**Comment by kakuilan** [comment]
2019数据已更新
