### ISSUE TITLE
请问您有获取到2009年、2010年、2011年村居级别的经纬度信息吗？

### ISSUE THREAD

**Issue by heyang95** [kakuilan/china_area_mysql#52]

**Comment by kakuilan** [comment]
没有哦，最早只有2013的

**Comment by heyang95** [comment]
请问可以提供下2013,2014，2015年的村居委会经纬度下载链接吗？谢谢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "K"<notifications@github.com&gt;; 
发送时间: 2021年1月31日(星期天) 上午10:05
收件人: "kakuilan/china_area_mysql"<china_area_mysql@noreply.github.com&gt;; 
抄送: "何洋"<393829124@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kakuilan/china_area_mysql] 请问您有获取到2009年、2010年、2011年村居级别的经纬度信息吗？ (#52)





 
没有哦，最早只有2013的

**Comment by kakuilan** [comment]
https://github.com/kakuilan/china_area_mysql/releases

**Comment by heyang95** [comment]
谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "K"<notifications@github.com&gt;; 
发送时间: 2021年2月2日(星期二) 上午9:26
收件人: "kakuilan/china_area_mysql"<china_area_mysql@noreply.github.com&gt;; 
抄送: "何洋"<393829124@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kakuilan/china_area_mysql] 请问您有获取到2009年、2010年、2011年村居级别的经纬度信息吗？ (#52)





 
https://github.com/kakuilan/china_area_mysql/releases
