### ISSUE TITLE
行政编号问题

### ISSUE THREAD

**Issue by wen-gg** [kakuilan/china_area_mysql#57]
如图：台湾、香港、澳门 不匹配
![image](https://user-images.githubusercontent.com/17865026/125718744-a616460f-6213-4f24-ae29-bd7bc4c574f1.png)
![image](https://user-images.githubusercontent.com/17865026/125718811-972f4bac-7a52-41fd-b336-de03f02ce415.png)

**Comment by kakuilan** [comment]
谢谢指正，已修改，请下载最新的v20200630

**Comment by wen-gg** [comment]
@kakuilan 大佬，你没有修改相应下级的上级ID

**Comment by kakuilan** [comment]
粗心了，已修改，再重新下载看看
