### ISSUE TITLE
请问是用什么方法“爬“出这些数据的呢？

### ISSUE THREAD

**Issue by GongShengyue** [kakuilan/china_area_mysql#6]

**Comment by kakuilan** [comment]
就是一页一页爬取国家统计局的数据，然后正则过滤数据，
ttp://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2015/

**Comment by RebieKong** [comment]
那么经纬度是从那边爬的呢？

**Comment by kakuilan** [comment]
百度地图有接口的

**Comment by RebieKong** [comment]
ok~

**Comment by herrygoon** [comment]
您好，看到你说坐标信息是从百度地图过来的，但是从百度地图中查询的时候，发现还有很大的差距。

**Comment by feibaliang** [comment]
请问简称是怎么获取的

**Comment by kakuilan** [comment]
> 
> 
> 请问简称是怎么获取的

程序去处理,比如景山街道办事处,取景山

**Comment by fengkaijia** [comment]
请问邮编是如何获取的？多谢

**Comment by kakuilan** [comment]
@fengkaijia 通过这个http://waiter.www.so.com/postcode/s?q=&prov=&city=&county=
