### ISSUE TITLE
不同年份的相同行政区的主键id可能会变化么？

### ISSUE THREAD

**Issue by ppoffice** [kakuilan/china_area_mysql#8]
如果某个地区的行政规划发生了变化，那么后续自增的主键id可能会发生变化，是不是应该在area_code上建立索引？

**Comment by kakuilan** [comment]
id是自增的，会变化；可以用area_code作索引，但不能是唯一索引，因为目前港澳台地区的area_code都是0

**Comment by ppoffice** [comment]
@kakuilan 感谢回复。因为考虑到行政区更新的时候主键变化将导致其他表相对于行政区表的外键失效，所以询问了这个问题……可能需要通过其他方式确保外键不变了。
